title: KCIJ_djschool # your site title
author: djschool
email: djschool@newstapa.org # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  KCIJ 데이터저널리즘 스쿨은 데이터를 기반으로 한 탐사보도의 저변 확대와 미래 데이터 저널리스트 양성을 위해 뉴스타파 데이터저널리즘연구소에서 기획한 비영리 교육 프로그램입니다.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://djschool.github.io" # the base hostname & protocol for your site, e.g. http://example.com
social:
  name: KCIJ_djschool
  links:
    - https://twitter.com/newstapa
    - https://www.facebook.com/NEWSTAPA
    - https://www.youtube.com/newstapa
    - https://github.com/djschool
    - https://www.instagram.com/newstapa

disqus:
  shortname: djschool # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
